[package]
name = "filter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dasp_ring_buffer = "*"
hound = "*"
dasp_signal = "*"
dasp_sample = "*"
dasp_frame = "*"